language: 
  - R

cache: 
  - packages
  
sudo:
  - required

warnings_are_errors: 
  - true

before_install:
  - chmod 755 ./travis-tool/travis_timeout.sh
  - sudo apt-get install libssl-dev
  - sudo apt-get install libcurl4-openssl-dev
  - sudo apt-get install libhdf5-7
  - sudo apt-get install libhdf5-dev
  - sudo apt-get install libudunits2-0
  - sudo apt-get install libudunits2-dev
  - export LD_LIBRARY_PATH=/usr/local/lib
  - wget ftp://ftp.unidata.ucar.edu/pub/netcdf/netcdf-4.4.1.tar.gz
  - tar xvzf netcdf-4.4.1.tar.gz
  - cd netcdf-4.4.1
  - ./configure
  - make check
  - sudo make install
  - cd ..

script: 
  - ./travis-tool/travis_timeout.sh travis_wait

## Use patched devtools
r_github_packages:
  - hadley/devtools@efa894ffa
